### PR TITLE
Take calldatasize into account for calldataload.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
Actually the test failure exposes a shortcoming in the encoding:
We say `calldataload(x) == 0 if x >= calldatasize()`, but we don't say that the last `k` bytes of `calldataload(x)` are zero if `x` is close to `calldatasize()`.
What should be do? Probably it's not too important to encode the property given in this PR.

**Comment by leonardoalt** [comment]
Why do those also need to be 0?

**Comment by leonardoalt** [comment]
There are `yul` files missing for 3 `smt2` tests

**Comment by leonardoalt** [comment]
Ah no, those are just test updates. I guess the branch just needs a rebase/update.

**Comment by chriseth** [comment]
They need to be zero for the shift test to work.

**Comment by leonardoalt** [comment]
Sorry, I still don't get it.
Are you talking about this test?
```
{
    let x := calldataload(0)
    let y := calldataload(1)
    x := shl(8, x)
    y := and(y, not(0xff))
    assert(eq(x, y))
}
```

**Comment by chriseth** [comment]
Yes. It asserts `(calldataload(0) << 8) == (calldataload(1) & ~0xff)`
Now the problem is that if `calldatasize()` is `1`, `calldataload(1)` returns zero, but the solver cannot reason that `calldataload(0) << 8` is zero as well.

**Comment by chriseth** [comment]
I guess the solution is to do the `ite` on the array access itself instead of for `calldataload`.

**Comment by chriseth** [comment]
Tried it on byte-level, but the test seems to be failing still.

**Comment by chriseth** [comment]
Superseded by https://github.com/leonardoalt/yools/pull/92

**Pull request closed without merging**
